### ISSUE TITLE
New release for Charm4Py 1.1

### ISSUE THREAD

**Issue by adityapb** [charmplusplus/charm4py#247]
- [x] Modernize pip infrastructure
- Build via cibuildwheel
- Package charm++ with charm4py, if possible (so that charm++ does not need to be built when running pip install charm4py)

- [x] Test with latest Python version
- [x] Merge ray implementation
- [x] Update to Cython 3.0

Later: 
Conda-forge (needs new license, see e.g. https://github.com/UIUC-PPL/charm/pull/3793)

**Comment by mayantaylor** [comment]
Pip modernization done in #267

**Comment by mayantaylor** [comment]
Charm4py v1.1 released in #250
